version: '3.8'
services:
  db_master:
    env_file:
      - environment.env
    build:
      context: .
      dockerfile: ./master/Dockerfile
    container_name: db_master
    hostname: db_master
    volumes:
       - master_data:/var/lib/mysql
       - ./master/log:/var/log/mysql
#       - ./master/conf.d: /etc/mysql/conf.d
       - ./master/init_data:/docker-entrypoint-initdb.d
       - ../work:/work
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_REPLICA_USER=${DB_REPLICA_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      #- MYSQL_RANDOM_ROOT_PASSWORD: 1
      - TZ=${TZ}
    ports:
      - "3306:3306"
  db_slave:
    env_file:
      - environment.env
    build:
      context: .
      dockerfile: ./slave/Dockerfile
    container_name: db_slave
    hostname: db_slave
    volumes:
       - slave_data:/var/lib/mysql
       - ./slave/log:/var/log/mysql
#       - ./read/conf.d:/etc/mysql/conf.d
       - ./slave/init_data:/docker-entrypoint-initdb.d
       - ../work:/work
    environment:
      - MYSQL_MASTER_HOST=db_master
#      - SOURCE_MYSQL_USER: ${DB_USER}
#      - SOURCE_MYSQL_PASSWORD: ${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_REPLICA_USER=${DB_REPLICA_USER}
      #- MYSQL_RANDOM_ROOT_PASSWORD=1
      - TZ=${TZ}
    depends_on:
      - db_master

volumes:
  master_data:
  slave_data:
